[package]
name = "economy"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
world-schema = { workspace = true }
tuning = { workspace = true }
directive-schema = { workspace = true }
sim-events = { workspace = true }
world-map = { workspace = true }
cohorts = { workspace = true }
nations = { workspace = true }
fauna = { workspace = true }

[dev-dependencies]
flora = { workspace = true }
species = { workspace = true }

[lints]
workspace = true
