[package]
name = "fauna"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
world-schema = { workspace = true }
tuning = { workspace = true }
sim-events = { workspace = true }
world-map = { workspace = true }
species = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
flora = { workspace = true }
