[package]
name = "structures"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
world-schema = { workspace = true }
tuning = { workspace = true }
world-map = { workspace = true }
regolith = { workspace = true }
geology = { workspace = true }

[dev-dependencies]
sim-events = { workspace = true }

[lints]
workspace = true
